name: Air Quality Data Crawler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl-air-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run Air Quality Data Crawler
      env:
        WAQI_API_KEY: ${{ secrets.WAQI_API_KEY }}
      run: |
        sed -i "s/API_KEY = \".*\"/API_KEY = \"$WAQI_API_KEY\"/g" air_quality_crawler.py
        python air_quality_crawler.py
    
    - name: Commit and push data        
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add result/*
        git diff --staged --quiet || git commit -m "Update AQI data [skip ci]"
        git push origin main