name: Air Quality Data Crawler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl-air-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run Air Quality Data Crawler
      env:
        WAQI_API_KEY: ${{ secrets.WAQI_API_KEY }}
      run: |
        python air_quality_crawler.py
    
    - name: Commit and push data
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add result/
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git commit -m "Add air quality data - $(date +'%Y-%m-%d %H:%M:%S')"
        git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git